[tool.bump_version]
version_file = "ollama_shell/__init__.py"

[tool.bump_version.replace_patterns.pipx]
file = "README.md"
search = "<!-- LATEST-VERSION-PIPX -->"
replace = "\tpipx install git+https://github.com/diversen/ollama-shell@{version}\n"
